<?php
/**
 * Created by PhpStorm.
 * User: wodrow
 * Date: 7/3/16
 * Time: 10:16 AM
 */

namespace app\controllers;

use Yii;
use app\models\User;
use yii\web\Controller;

class InitController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        User::$users = Yii::$app->params['adminUsers'];
    }
}