<?php

namespace app\modules\products\models;

use app\components\Tools;

class Products extends \app\models\Products
{
    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        $this->thumb = self::getThumbUrl($this->thumb);
    }
}
